from app.models.role import Role
from app.models.user import User
from app.models.ticket import Ticket
from app.models.ticket_history import TicketHistory
from app.models.comment import Comment
from app.models.attachment import Attachment
from app.models.notification import Notification
from app.models.activity_log import ActivityLog
from app.models.company import Company
from app.models.application import Application
from app.models.ticket_reminder import TicketReminder
from app.models.telegram_link_token import TelegramLinkToken