"""create attachments table

Revision ID: 18552771dafb
Revises: e290a0460391
Create Date: 2026-08-02 23:41:39.129023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, us
# ed by Alembic.
revision: str = '18552771dafb'
down_revision: Union[str, Sequence[str], None] = 'e290a0460391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
