"""add ticket reminder.1

Revision ID: dc924859b35e
Revises: 328d04fd44c2
Create Date: 2026-10-01 15:05:18.736201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc924859b35e'
down_revision: Union[str, Sequence[str], None] = '328d04fd44c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'reminder_type', name='uq_ticket_reminder_type')
    )
    op.create_index(op.f('ix_ticket_reminders_id'), 'ticket_reminders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_reminders_id'), table_name='ticket_reminders')
    op.drop_table('ticket_reminders')
    # ### end Alembic commands ###
